swagger: '2.0'
info:
  description: API para la integración con el Sistema de Gestión Personas.
  title: API-SGP
  version: 1.0.0
host: 'localhost:8080'
basePath: /sgp
schemes:
  - http
paths:
  /usuarios:
    get:
      produces:
        - application/json
      parameters:
        - description: Nº de pagina
          format: int32
          in: header
          minimum: 0
          name: X-Page
          type: integer
          x-example: 2
        - description: Nº de elementos por página
          format: int32
          in: header
          minimum: 0
          name: X-Page-Size
          type: integer
          x-example: 10
        - description: >-
            Criterios de busqueda. <hr> Lista de criterios de busqueda separada
            por comas, donde un criterio de busqueda es el nombre de uno de los
            campos de la entidad buscada seguido de la operación y el valor con
            el que se hace la comparación. Las operaciones soportadas son: <ul>
            <li><b>:</b> equals</li> <li><b>!:</b> not equals</li> <li><b>~</b>
            like</li> <li><b>!~</b> not like</li> <li><b>></b> greather</li>
            <li><b>>:</b> greather or equal</li> <li><b><</b> lower</li>
            <li><b><:</b> lower or equal</li></ul>
          in: query
          name: q
          type: string
          x-example: 'usuarioRef!~p00,primerApellido:perez'
        - description: >-
            Criterios de ordenación de la busqueda. <hr/> Nombre del campo por
            el que se ordena seguido de +/- para ordenar ascendente o
            descendentemente.
          in: query
          name: s
          type: string
          x-example: nombre-
      responses:
        '200':
          description: successful operation
          headers:
            X-Page:
              description: Nº de página
              type: integer
            X-Page-Count:
              description: Nº de páginas
              type: integer
            X-Page-Size:
              description: Nº de elementos por página
              type: integer
            X-Page-Total-Count:
              description: Nº de elementos en la página
              type: integer
            X-Total-Count:
              description: Nº total de elementos
              type: integer
          schema:
            items:
              $ref: '#/definitions/Usuario'
            type: array
        '204':
          description: No hay usuarios para los criterios de busqueda utilizados.
        '400':
          description: Invalid params
      tags:
        - usuario
      description: >-
        Devuelve la lista paginada con los datos básicos de los usuarios que
        cumplen los filtros.
      operationId: findAllUsuarios
      summary: Busca usuarios
  '/usuarios/{usuarioRef}':
    get:
      produces:
        - application/json
      parameters:
        - description: Referencia del usuario
          in: path
          name: usuarioRef
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Usuario'
        '400':
          description: usuarioRef no valido
        '404':
          description: usuario no encontrado
      tags:
        - usuario
      description: Devuelve el usuario correspondiente a usuarioRef
      operationId: findUsuarioByUsuarioRef
      summary: Busca un usuario por su usuarioRef
  '/usuariosinfo/{usuarioRef}':
    get:
      produces:
        - application/json
      parameters:
        - description: Referencia del usuario
          in: path
          name: usuarioRef
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/UsuarioInfo'
        '400':
          description: usuarioRef no valido
        '404':
          description: usuario no encontrado
      tags:
        - usuarioInfo
      description: Devuelve el usuario correspondiente a usuarioRef
      operationId: findUsuarioInfoByUsuarioRef
      summary: Busca un usuario por su usuarioRef
definitions:
  DatosEmail:
    properties:
      email:
        type: string
      tipoEmail:
        type: string
    type: object
  DatosTelefono:
    properties:
      telefono:
        type: string
      tipoTelefono:
        type: string
    type: object
  Domicilio:
    properties:
      codigoPostal:
        type: string
      nombreVia:
        type: string
      numero:
        type: string
      pais:
        type: string
      poblacion:
        type: string
      provincia:
        type: string
      tipoVia:
        $ref: '#/definitions/TipoVia'
    type: object
  Profesional:
    properties:
      categoriaProfesional:
        type: string
      cuerpoProfesional:
        type: string
      profesionalRef:
        type: string
      subcuerpoProfesional:
        type: string
    type: object
  TipoIdentificadorPersonal:
    properties:
      codigo:
        type: string
      descripcion:
        type: string
      tipoIdentificadorRef:
        type: string
    type: object
  TipoVia:
    properties:
      telefono:
        type: string
      tipoTelefono:
        type: string
    type: object
  Usuario:
    properties:
      email:
        type: string
      nombre:
        type: string
      primerApellido:
        type: string
      segundoApellido:
        type: string
      usuarioRef:
        type: string
    required:
      - nombre
      - primerApellido
    type: object
  UsuarioInfo:
    properties:
      datosEmail:
        $ref: '#/definitions/DatosEmail'
      datosTelefono:
        $ref: '#/definitions/DatosTelefono'
      domicilio:
        $ref: '#/definitions/Domicilio'
      fechaNacimiento:
        type: string
      nacionalidad:
        type: string
      numIdentificadorPersonal:
        type: string
      profesional:
        $ref: '#/definitions/Profesional'
      sexo:
        type: string
      tipoIdentificador:
        $ref: '#/definitions/TipoIdentificadorPersonal'
      usuario:
        $ref: '#/definitions/Usuario'
      vinculacion:
        type: string
    type: object
tags:
  - externalDocs:
      description: Find out more
      url: 'https://confluence.treelogic.com/display/HERCULES/SGI+-+ESB+-+SGP'
    description: Operaciones con datos básicos de usuario
    name: usuario
  - externalDocs:
      description: Find out more
      url: 'https://confluence.treelogic.com/display/HERCULES/SGI+-+ESB+-+SGP'
    description: Operaciones con datos completos de usuario
    name: usuarioInfo
externalDocs:
  description: Find out more about SGP
  url: 'https://confluence.treelogic.com/display/HERCULES/SGI+-+ESB+-+SGP'
x-components: {}

