
title: "[UNIVERSIDAD][COMPONENTE] ..."
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Usa esta categor铆a para realizar **preguntas o dudas concretas** sobre el funcionamiento del sistema.

        锔 **No utilices este formulario para proponer mejoras o nuevas funcionalidades**  
         Para eso, usa la categor铆a **Ideas**.

         Comprueba que tu consulta no existe previamente, si esa as铆 a帽ade un comentario 
         Si se trata de un **error cr铆tico en producci贸n**, crea directamente un **GitHub Issue**.

  - type: textarea
    id: pregunta
    attributes:
      label: Pregunta o duda
      description: Describe claramente cu谩l es tu duda.
      placeholder: 驴C贸mo funciona...? / 驴Es posible configurar...? / 驴Por qu茅 ocurre...?
    validations:
      required: true

  - type: textarea
    id: contexto
    attributes:
      label: Contexto
      description: Proporciona informaci贸n adicional que ayude a entender la pregunta.
      placeholder: M贸dulo afectado, caso de uso, pasos realizados, etc.
    validations:
      required: false

  - type: dropdown
    id: entorno
    attributes:
      label: Entorno
      description: 驴En qu茅 entorno ocurre?
      options:
        - Producci贸n
        - Preproducci贸n
        - Desarrollo
        - No aplica
    validations:
      required: true

  - type: dropdown
    id: tipo
    attributes:
      label: Tipo de consulta
      description: Selecciona la opci贸n que mejor describa tu duda.
      options:
        - Duda funcional
        - Duda t茅cnica
        - Comportamiento inesperado
        - Documentaci贸n
        - Otro
    validations:
      required: true

  - type: textarea
    id: evidencias
    attributes:
      label: Evidencias o informaci贸n adicional
      description: Incluye mensajes de error, capturas o enlaces relevantes (si aplica).
      placeholder: capturas de pantalla, mensajes de error, enlaces, etc.
    validations:
      required: false

