-- FORMULARIO
INSERT INTO ETI.FORMULARIO
(ID, NOMBRE, DESCRIPCION, ACTIVO)
VALUES(1, 'M10', 'Descripcion1', true);

-- BLOQUE FORMULARIO
INSERT INTO ETI.BLOQUE_FORMULARIO
(ID, NOMBRE, FORMULARIO_ID, ORDEN, ACTIVO)
VALUES(1, 'BloqueFormulario1', 1, 1, true);
INSERT INTO ETI.BLOQUE_FORMULARIO
(ID, NOMBRE, FORMULARIO_ID, ORDEN, ACTIVO)
VALUES(2, 'BloqueFormulario2', 1, 2, true);

-- COMPONENTE FORMULARIO
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(1, 'EsquemaComponenteFormulario1');

-- APARTADO FORMULARIO
INSERT INTO ETI.APARTADO_FORMULARIO
(ID, BLOQUE_FORMULARIO_ID, NOMBRE, APARTADO_FORMULARIO_PADRE_ID, ORDEN, COMPONENTE_FORMULARIO_ID, ACTIVO)
VALUES(1, 1, 'ApartadoFormulario01', NULL, 1, 1, true);

INSERT INTO ETI.APARTADO_FORMULARIO
(ID, BLOQUE_FORMULARIO_ID, NOMBRE, APARTADO_FORMULARIO_PADRE_ID, ORDEN, COMPONENTE_FORMULARIO_ID, ACTIVO)
VALUES(2, 1, 'ApartadoFormulario2', 1, 2, 1, true);