-- FORMULARIO
INSERT INTO ETI.FORMULARIO
(ID, NOMBRE, DESCRIPCION, ACTIVO)
VALUES(1, 'M10', 'Descripcion1', true);

-- BLOQUE FORMULARIO
INSERT INTO ETI.BLOQUE_FORMULARIO
(ID, NOMBRE, FORMULARIO_ID, ORDEN, ACTIVO)
VALUES(1, 'BloqueFormulario1', 1, 1, true);

-- COMPONENTE FORMULARIO
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(1, 'EsquemaComponenteFormulario1');