-- COMPONENTE FORMULARIO
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(1, 'EsquemaComponenteFormulario01');
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(2, 'EsquemaComponenteFormulario2');
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(3, 'EsquemaComponenteFormulario03');
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(4, 'EsquemaComponenteFormulario4');
INSERT INTO ETI.COMPONENTE_FORMULARIO
(ID, ESQUEMA)
VALUES(5, 'EsquemaComponenteFormulario05');