-- ESTADO RETROSPECTIVA
INSERT INTO ETI.ESTADO_RETROSPECTIVA (ID, NOMBRE, ACTIVO) VALUES (1, 'EstadoRetrospectiva01', true);

INSERT INTO ETI.ESTADO_RETROSPECTIVA (ID, NOMBRE, ACTIVO) VALUES (2, 'EstadoRetrospectiva2', true);

-- RETROSPECTIVA
INSERT INTO ETI.RETROSPECTIVA(ID, ESTADO_RETROSPECTIVA_ID, FECHA_RETROSPECTIVA) VALUES (3, 1, '2020-07-03');

INSERT INTO ETI.RETROSPECTIVA(ID, ESTADO_RETROSPECTIVA_ID, FECHA_RETROSPECTIVA) VALUES (4, 2, '2020-07-04');

INSERT INTO ETI.RETROSPECTIVA(ID, ESTADO_RETROSPECTIVA_ID, FECHA_RETROSPECTIVA) VALUES (5, 1, '2020-07-05');

INSERT INTO ETI.RETROSPECTIVA(ID, ESTADO_RETROSPECTIVA_ID, FECHA_RETROSPECTIVA) VALUES (6, 2, '2020-07-06');

INSERT INTO ETI.RETROSPECTIVA(ID, ESTADO_RETROSPECTIVA_ID, FECHA_RETROSPECTIVA) VALUES (7, 1, '2020-07-07');

