server:
  port : 4295
  error:
    whitelabel:
      # Disble the default error page displayed in browsers in case of a server error
      enabled: false

spring:
  profiles:
    # Set spring-profile using maven
    include: @spring.profiles.active@
  jpa:
    # Disable Open Session In View
    open-in-view: false
  liquibase:
    # No Liquibase contexts
    contexts: none
  autoconfigure:
    # Disable security
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
---
spring:
  profiles: dev
  datasource:
    # Make sure database schema is created (schema.sql is executed)
    initialization-mode: always
    # We use a H2 in file database with PostgreSQL compatibility mode
    url: "jdbc:h2:./target/db/sgdoc;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    # Enable Liquibase
    enabled: true
    # Default database schema
    default-schema: sgdoc
    # Schema to use for Liquibase objects
    liquibase-schema: sgdoc
    # Set Liquibase contexts same as spring profiles
    contexts: dev
  jpa:
    hibernate:
      # Make sure Hibernate will not use the entities to create, update or validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use a H2 database with PostgreSQL compatibility mode
        dialect: org.hibernate.dialect.H2Dialect
        # Set default Hibernate schema
        default_schema: sgdoc
  # H2 console
  h2:
    console:
      enabled: false
      #path: /h2-console
      #settings:
        #web-allow-others: true

logging:
  level:
    org:
      hibernate:
        # Log the SQL statements
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # Log SQL query parameter binding
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            # Log JdbcTemplate Queries
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
---
spring:
  profiles: prod
  datasource:
    # Make sure database schema is created (schema.sql is executed)
    initialization-mode: always
    # We use PostgreSQL database
    url: "jdbc:postgresql://postgres:5432/sgdoc"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    # Enable Liquibase
    enabled: true
    # Default database schema
    default-schema: sgdoc
    # Schema to use for Liquibase objects
    liquibase-schema: sgdoc
  jpa:
    hibernate:
      # Hibernate will use the entities to validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use a PostgreSQL database
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        # Set default Hibernate Schema
        default_schema: sgdoc
