export const CSP_ROUTE_NAMES = {
  CONVOCATORIA: 'convocatoria',
  SOLICITUD: 'solicitud',
  FUENTE_FINANCIACION: 'fuente-financiacion',
  TIPO_DOCUMENTO: 'tipo-documentos',
  TIPO_FINALIDAD: 'tipo-finalidades',
  TIPO_ENLACE: 'tipo-enlaces',
  TIPO_HITO: 'tipo-hitos',
  TIPO_FASE: 'tipo-fases',
  MODELO_EJECUCION: 'modelo-ejecuciones',
  PLANES_INVESTIGACION: 'planes-investigacion',
  CONCEPTO_GASTO: 'concepto-gasto',
  TIPO_FINANCIACION: 'tipo-financiaciones',
  AREA_TEMATICA: 'area-tematica',
  PROYECTO: 'proyectos',
  SOLICITUD_PROYECTO_SOCIO: 'solicitud-proyecto-socio',
  PROYECTO_SOCIO: 'proyecto-socio',
  PROYECTO_SEGUIMIENTO_CIENTIFICO: 'proyecto-seguimiento-cientifico',
  PROYECTO_SOCIO_PERIODO_JUSTIFICACION: 'proyecto-socio-periodo-justificacion',
  PROYECTO_PRORROGA: 'proyecto-prorroga'
};
