swagger: '2.0'
info:
  description: API para la integración con el Sistema de Gestión Económica.
  title: API-SGE
  version: 1.0.0
host: 'localhost:8080'
basePath: /sge
schemes:
  - http
paths:
  /codigoeconomicos/gastos:
    get:
      produces:
        - application/json
      parameters:
        - description: Nº de pagina
          format: int32
          in: header
          minimum: 0
          name: X-Page
          required: false
          type: integer
          x-example: 2
        - description: Nº de elementos por página
          format: int32
          in: header
          minimum: 0
          name: X-Page-Size
          required: false
          type: integer
          x-example: 10
        - description: >-
            Criterios de busqueda. <hr> Lista de criterios de busqueda separada
            por comas, donde un criterio de busqueda es el nombre de uno de los
            campos de la entidad buscada seguido de la operación y el valor con
            el que se hace la comparación. Las operaciones soportadas son: <ul>
            <li><b>:</b> equals</li> <li><b>!:</b> not equals</li> <li><b>~</b>
            like</li> <li><b>!~</b> not like</li> <li><b>></b> greather</li>
            <li><b>>:</b> greather or equal</li> <li><b><</b> lower</li>
            <li><b><:</b> lower or equal</li></ul>
          in: query
          name: q
          required: false
          type: string
          x-example: 'codigoEconomicoRef!~tr0,codigo>100'
        - description: >-
            Criterios de ordenación de la busqueda. <hr/> Nombre del campo por
            el que se ordena seguido de +/- para ordenar ascendente o
            descendentemente.
          in: query
          name: s
          required: false
          type: string
          x-example: codigoEconomicoRef-
      responses:
        '200':
          description: successful operation
          headers:
            X-Page:
              description: Nº de página
              type: integer
            X-Page-Count:
              description: Nº de páginas
              type: integer
            X-Page-Size:
              description: Nº de elementos por página
              type: integer
            X-Page-Total-Count:
              description: Nº de elementos en la página
              type: integer
            X-Total-Count:
              description: Nº total de elementos
              type: integer
          schema:
            items:
              $ref: '#/definitions/CodigoEconomico'
            type: array
        '204':
          description: >-
            No hay codigos economicos de tipo gasto para los criterios de
            busqueda utilizados.
        '400':
          description: Invalid params
      tags:
        - codigoeconomicos
      description: >-
        Devuelve la lista paginada con los codigos economicos de tipo gasto que
        cumplen los filtros.
      operationId: findAllCodigoEconomicosGasto
      summary: Busca codigos economicos de tipo gasto
  /codigoeconomicos/ingresos:
    get:
      produces:
        - application/json
      parameters:
        - description: Nº de pagina
          format: int32
          in: header
          minimum: 0
          name: X-Page
          required: false
          type: integer
          x-example: 2
        - description: Nº de elementos por página
          format: int32
          in: header
          minimum: 0
          name: X-Page-Size
          required: false
          type: integer
          x-example: 10
        - description: >-
            Criterios de busqueda. <hr> Lista de criterios de busqueda separada
            por comas, donde un criterio de busqueda es el nombre de uno de los
            campos de la entidad buscada seguido de la operación y el valor con
            el que se hace la comparación. Las operaciones soportadas son: <ul>
            <li><b>:</b> equals</li> <li><b>!:</b> not equals</li> <li><b>~</b>
            like</li> <li><b>!~</b> not like</li> <li><b>></b> greather</li>
            <li><b>>:</b> greather or equal</li> <li><b><</b> lower</li>
            <li><b><:</b> lower or equal</li></ul>
          in: query
          name: q
          required: false
          type: string
          x-example: 'codigoEconomicoRef!~tr0,codigo>100'
        - description: >-
            Criterios de ordenación de la busqueda. <hr/> Nombre del campo por
            el que se ordena seguido de +/- para ordenar ascendente o
            descendentemente.
          in: query
          name: s
          required: false
          type: string
          x-example: codigoEconomicoRef-
      responses:
        '200':
          description: successful operation
          headers:
            X-Page:
              description: Nº de página
              type: integer
            X-Page-Count:
              description: Nº de páginas
              type: integer
            X-Page-Size:
              description: Nº de elementos por página
              type: integer
            X-Page-Total-Count:
              description: Nº de elementos en la página
              type: integer
            X-Total-Count:
              description: Nº total de elementos
              type: integer
          schema:
            items:
              $ref: '#/definitions/CodigoEconomico'
            type: array
        '204':
          description: >-
            No hay codigos economicos de tipo gasto para los criterios de
            busqueda utilizados.
        '400':
          description: Invalid params
      tags:
        - codigoeconomicos
      description: >-
        Devuelve la lista paginada con los codigos economicos de tipo ingreso
        que cumplen los filtros.
      operationId: findAllCodigoEconomicosIngreso
      summary: Busca codigos economicos de tipo ingreso
  '/codigoeconomicos/{id}':
    get:
      produces:
        - application/json
      parameters:
        - description: Referencia del codigo economico
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CodigoEconomico'
        '400':
          description: id no valido
        '404':
          description: codigo economico no encontrado
      tags:
        - codigoeconomicos
      description: Devuelve el codigo economico correspondiente al identificador
      operationId: findCodigoEconomicoByCodigoEconomicoRef
      summary: Busca un codigo economico por su identificador
definitions:
  CodigoEconomico:
    properties:
      codigo:
        type: string
      codigoEconomicoRef:
        description: Identificador del codigo economico
        type: string
      fechaFin:
        type: string
      fechaInicio:
        type: string
    type: object
tags:
  - description: Operaciones con codigos economicos
    name: codigoeconomicos
externalDocs:
  description: Find out more about SGE
  url: 'https://confluence.treelogic.com/display/HERCULES/SGI+-+ESB+-+SGE'
x-components: {}

