server:
  port : 4289
  error:
    whitelabel:
      # Disble the default error page displayed in browsers in case of a server error
      enabled: false
sgi:
  time-zone: "Europe/Madrid"
  web-url: "http://localhost:4200"
  rest:
    api:
      cnf-url: "http://localhost:4288"
      com-url: "http://localhost:4286"
      csp-url: "http://localhost:4281"
      pii-url: "http://localhost:4283"
      rel-url: "http://localhost:4284"
      rep-url: "http://localhost:4287"
      sgo-url: "http://localhost:8290/sgo"
      sgepii-url: "http://localhost:8290/sgepii"
      sgp-url: "http://localhost:8290/sgp"
      tp-url:  "http://localhost:4285"

spring:
  profiles:
    # Set spring-profile using maven
    active: @spring.profiles.active@
  datasource:
    # We use a H2 in file database with PostgreSQL compatibility mode
    url: "jdbc:h2:./target/db/prc;MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: prc
    password: prc
  # H2 console
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      # Make sure Hibernate will not use the entities to create, update or validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    # Disable Open Session In View
    open-in-view: false
    # Extra Hibernate properties
    properties:
      hibernate:
        # We use a H2 database with PostgreSQL compatibility mode
        dialect: org.hibernate.dialect.H2Dialect
        # Set default Hibernate schema
        '[default_schema]': ${spring.datasource.username}
        jdbc:
          # see: https://vladmihalcea.com/how-to-store-date-time-and-timestamps-in-utc-time-zone-with-jdbc-and-hibernate/
          '[time_zone]': UTC
  liquibase:
    # No Liquibase contexts
    contexts: none
    # Default database schema
    default-schema: ${spring.jpa.properties.hibernate.[default_schema]}
    # Enable Liquibase
    enabled: true
    # Schema to use for Liquibase objects
    liquibase-schema: ${spring.jpa.properties.hibernate.[default_schema]}
    # Set Liquibase changeLog parameters
    parameters:
      schemaPrefix: ${spring.jpa.properties.hibernate.[default_schema]}.
  mvc:
    # Retain ant path controller definitions
    pathmatch:
      matching-strategy: ant-path-matcher
    # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      client:
        registration:
          # "sgi" is the id used inside the redirect-uri-template, must be the same as your realm
          sgi:
            authorization-grant-type: authorization_code
            client-id: front
            client-name: SGI (user login)
            provider: keycloak
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "openid,profile"
          prc-service:
            authorization-grant-type: client_credentials
            client-id: prc-service
            client-name: SGI (service login)
            client-secret: a57a856d-5136-42d9-8baa-6e2bdb962a2e
            provider: keycloak
            scope: sgi-cnf,sgi-com,sgi-csp,sgi-pii,sgi-rel,sgi-rep,sgi-sgepii,sgi-sgo,sgi-sgp,sgi-tp          
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/sgi
            user-name-attribute: user_ref_id
      resourceserver:
        jwt:
          # JSON Web Key endpoint (with the cryptographic key to validate JSON Web Signature)
          jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
          user-name-claim: user_ref_id
  web:
    resources:
      # Disable the static resource handling
      add-mappings: false

preliquibase:
  enabled: false
---
spring:
  config:
    activate:
      on-profile:
      - dev
  liquibase:
    # Set Liquibase contexts same as spring profiles
    contexts: dev  
#  # H2 console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  security:
#    oauth2:
#      # Enable login page if JWT not provided (enable only for development)
#      enable-login: true
#    # Disable CSRF (disable only for development)
#    csrf:
#      enable: false
#    # Disable X-Frame-Options (disable only for development)
#    frameoptions:
#      enable: false
preliquibase:
  enabled: true
logging:
  level:
    org:
      hibernate:
        # Log the SQL statements
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # Log SQL query parameter binding
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            # Log JdbcTemplate Queries
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
---
spring:
  config:
    activate:
      on-profile:
      - dev-oracle
  datasource:
    # We use Oracle database
    url: jdbc:oracle:thin:@oracle12c:1521/ORCLPDB1.localdomain
    driver-class-name: oracle.jdbc.OracleDriver
    username: PRC_SGI
    password: PRC_SGI
  jpa:
    hibernate:
      # Make sure Hibernate will not use the entities to create, update or validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use Oracle database
        dialect: org.hibernate.dialect.Oracle12cDialect
  liquibase:
    # Set Liquibase contexts same as spring profiles
    contexts: dev
logging:
  level:
    org:
      hibernate:
        # Log the SQL statements
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # Log SQL query parameter binding
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            # Log JdbcTemplate Queries
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
---
spring:
  config:
    activate:
      on-profile:
      - dev-sqlserver
  datasource:
    # We use SQL Server database
    url: jdbc:sqlserver://sqlserver:1433;databaseName=SGI
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: PRC_SGI
    password: PRC_SGI_2021
  jpa:
    hibernate:
      # Make sure Hibernate will not use the entities to create, update or validate the database
      # validate | update | create | create-drop
      ddl-auto: none
    properties:
      hibernate:
        # We use SQL Server database
        dialect: org.hibernate.dialect.SQLServer2016Dialect
  liquibase:
    # Set Liquibase contexts same as spring profiles
    contexts: dev
logging:
  level:
    org:
      hibernate:
        # Log the SQL statements
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # Log SQL query parameter binding
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            # Log JdbcTemplate Queries
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
---
sgi:
  rest:
    api:
      cnf-url: "http://sgi-cnf-service:8080"
      com-url: "http://sgi-com-service:8080"
      csp-url: "http://sgi-csp-service:8080"
      pii-url: "http://sgi-pii-service:8080"
      rel-url: "http://sgi-rel-service:8080"
      rep-url: "http://sgi-rep-service:8080"
      sgo-url: "http://sgi-esb:8080/sgo"
      sgepii-url: "http://sgi-esb:8080/sgepii"
      sgp-url: "http://sgi-esb:8080/sgp"
      tp-url:  "http://sgi-tp-service:8080"

spring:
  config:
    activate:
      on-profile:
      - prod
  datasource:
    # We use PostgreSQL database
    url: "jdbc:postgresql://postgres:5432/prc"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        # We use a PostgreSQL database
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        # Set default Hibernate Schema
        '[default_schema]': prc
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://sgi-auth:8080/auth/realms/sgi
