-- vacia la bd
DELETE FROM eti.documentacion_memoria
DELETE FROM eti.tarea
DELETE FROM eti.informe_formulario
DELETE FROM eti.estado_memoria
DELETE FROM eti.evaluador_evaluacion
DELETE FROM eti.evaluacion
DELETE FROM eti.formulario_memoria
DELETE FROM eti.memoria
DELETE FROM eti.tipo_memoria_comite
DELETE FROM eti.asistentes
DELETE FROM eti.evaluador
DELETE FROM eti.evaluacion
DELETE FROM eti.equipo_trabajo
DELETE FROM eti.peticion_evaluacion
DELETE FROM eti.tipo_actividad
DELETE FROM eti.tipo_memoria
DELETE FROM eti.tipo_documento
DELETE FROM eti.estado_acta
DELETE FROM eti.acta
DELETE FROM eti.tipo_estado_acta
DELETE FROM eti.convocatoria_reunion
DELETE FROM eti.tipo_convocatoria_reunion
DELETE FROM eti.apartado_formulario
DELETE FROM eti.componente_formulario
DELETE FROM eti.bloque_formulario
DELETE FROM eti.comite_formulario
DELETE FROM eti.comite
DELETE FROM eti.tipo_estado_memoria
DELETE FROM eti.formacion_especifica
DELETE FROM eti.cargo_comite
DELETE FROM eti.dictamen
DELETE FROM eti.tipo_comentario
DELETE FROM eti.formulario
DELETE FROM eti.componente_formulario
DELETE FROM eti.configuracion
