name: SGI Framework Angular

on: 
  workflow_dispatch: 
  push:
    paths: 
      - 'sgi-framework-angular/**'
      - '.github/workflows/sgi-framework-angular.yml'
    branches:
      - ci

defaults:
  run:
    working-directory: sgi-framework-angular

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 14
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install chrome
      uses: browser-actions/setup-chrome@v2

    - name: Install dependencias
      run: npm install
    
    - name: Run tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
    
    - name: SonarQube analysis
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      with:
        projectBaseDir: sgi-framework-angular
        args: >
          -Dsonar.organization=herculesproject
          -Dsonar.projectKey=herculesproject_sgi_framework-angular
          -Dsonar.sources=projects/sgi/framework
          -Dsonar.tests=projects/sgi/framework
          -Dsonar.inclusions=**/*.ts
          -Dsonar.exclusions=**/*.spec.ts,test.ts
          -Dsonar.test.inclusions=**/*.spec.ts,test.ts
          -Dsonar.javascript.lcov.reportPaths=./coverage/sgi/framework/lcov.info
          -Dsonar.branch.name=main
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Build
      run: |
        cd projects/sgi/framework
        export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
        npm version --commit-hooks=false --git-tag-version=false $VERSION.$(date +%Y%m%d%H%M%S)
        cd ../../..
        npm run build -- --prod

    - name: Publish
      run: npm publish --provenance --access public dist/sgi/framework
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

   
